### ISSUE TITLE
Hint: text label on points of LDAplot and PCAplot

### ISSUE THREAD

**Issue by tassanom** [eead-csic-eesa/fingerPro#1]
I think it would be nice if the points of the LDA and PCA plots had a text label associated with the "Code" column of the .csv input.
It would facilitate the identification of ungrouped points or outsiders.

Keep up the good work!

**Comment by ivanlizaga** [comment]
I think it's a great idea and will help users to identify outliers or points wrongly assigned.
Please take a look at the new LDAPlot function I have just uploaded to the repository. I have included an additional boolean called "text". If you set it as TRUE, it will include the id numbers of each point. Here you can check the results when applied to the example dataset "catchment".

![image](https://user-images.githubusercontent.com/30837036/111654474-139be880-8809-11eb-8315-4d241afa7280.png)
